version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - echo "Current directory:" && pwd
      - echo "Directory contents:" && ls -la
      - echo "App directory contents:"
      - ls -la app/
      - echo "Installing with npm ci..."
      - cd app && npm ci --verbose
  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      - echo "Current directory:" && pwd
      - echo "Checking Node.js and npm versions"
      - cd $CODEBUILD_SRC_DIR/app && node --version && npm --version
      - echo "Checking package.json:"
      - cd $CODEBUILD_SRC_DIR/app && cat package.json
      - echo "Getting API Gateway URL from AWS..."
      - API_ID=$(aws apigateway get-rest-apis --region ap-northeast-2 --query 'items[?name==`devpuppy-dev-contact-api-4b5c150a`].id' --output text)
      - |
        if [ ! -z "$API_ID" ] && [ "$API_ID" != "None" ]; then 
          export NEXT_PUBLIC_API_GATEWAY_URL="https://$API_ID.execute-api.ap-northeast-2.amazonaws.com/dev"
          echo "Set NEXT_PUBLIC_API_GATEWAY_URL=$NEXT_PUBLIC_API_GATEWAY_URL"
        else 
          echo "Warning: Could not find API Gateway, using fallback"
        fi
  build:
    commands:
      - echo "Build phase started on `date`"
      - echo "Current directory:" && pwd
      - echo "Building Next.js application..."
      - cd $CODEBUILD_SRC_DIR/app && npm run build --verbose
      - echo "Build completed, checking output:"
      - cd $CODEBUILD_SRC_DIR/app && ls -la out/
  post_build:
    commands:
      - echo "Post-build phase started on `date`"
      - echo "Current directory:" && pwd
      - echo "Syncing files to S3 bucket $S3_BUCKET"
      - aws s3 sync $CODEBUILD_SRC_DIR/app/out/ s3://$S3_BUCKET --delete
      - echo "Creating CloudFront invalidation for distribution $CLOUDFRONT_DISTRIBUTION_ID"
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
      - echo "Deployment completed successfully"

artifacts:
  files:
    - '**/*'
  base-directory: app/out
  name: website-build

cache:
  paths:
    - app/node_modules/**/*
