version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      - echo "Checking Node.js and npm versions"
      - node --version
      - npm --version
  build:
    commands:
      - echo "Build phase started on `date`"
      - echo "Building Next.js application..."
      - npm run build
      - npx next export
      - echo "Build completed successfully"
  post_build:
    commands:
      - echo "Post-build phase started on `date`"
      - echo "Syncing files to S3 bucket $S3_BUCKET"
      - aws s3 sync out/ s3://$S3_BUCKET --delete
      - echo "Creating CloudFront invalidation for distribution $CLOUDFRONT_DISTRIBUTION_ID"
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
      - echo "Deployment completed successfully"

artifacts:
  files:
    - '**/*'
  base-directory: out
  name: website-build

cache:
  paths:
    - node_modules/**/*
