import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white min-h-screen`}
      >
        <div className="flex min-h-screen">
          {/* Sidebar */}
          <aside className="w-64 bg-neutral-900 border-r border-neutral-800 flex flex-col items-center py-8 px-4">
            {/* Logo */}
            <div className="mb-12 flex flex-col items-center">
              <div className="w-14 h-14 bg-yellow-400 rounded-full flex items-center justify-center text-3xl font-bold shadow-lg border-4 border-neutral-800">
                🐶
              </div>
              <span className="mt-2 text-xl font-bold tracking-tight text-white">DevPuppy</span>
            </div>
            {/* Navigation */}
            <nav className="flex flex-col gap-6 w-full">
              <a href="/" className="text-neutral-200 font-medium hover:text-yellow-300 transition-colors">Home</a>
              <a href="/projects" className="text-neutral-200 font-medium hover:text-yellow-300 transition-colors">Projects</a>
              <a href="/info" className="text-neutral-200 font-medium hover:text-yellow-300 transition-colors">Info</a>
              <a href="/contact" className="text-neutral-200 font-medium hover:text-yellow-300 transition-colors">Contact</a>
            </nav>
          </aside>
          {/* Main Content */}
          <main className="flex-1 px-8 py-10">{children}</main>
        </div>
      </body>
    </html>
  );
}
